Set "disable-ha=true" because HA is not enabled.
tektoncd/operator pull request #1445
Opened 2023-04-12 18:40 UTC by yocum137

HA tekton is not yet enabled, no need to enable it, now.  

The default has been incorrectly set to "false," i.e., it's _enabling_ HA. This is impacting customer pipelines.

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

2023-04-13 12:22 UTC, vdemeester requested changes
Hey @yocum137, thanks for the PR. but :
- This is on a vendor dependency, we do not edit directly vendor code (as they would be 
overwritten next time we update it). 
- This would only affect the tektoncd/operator controller and none of the operand (so the pipeline operator, trigger operator, …)

The required change is, more likely, to update the deployment of the tektoncd/operator controller (and webhook) as well as having a *transformer* to updates this on the operand's controllers.

I am still a bit fuzzy in how it impacts customer pipelines. What usually impacts customer pipelines is the number of PipelineRun (and other objects) that are on the cluster at a given time, *and* some performance flags on the controller. The *leader-election* thing is usually not adding any overhead.

2023-04-17 17:07 UTC, khrm reviewed
/ok-to-test

2023-04-17 17:10 UTC, khrm commented
Tests should fail because we don't modify vendor code as Vincent said. Just checking whether it happens here like in the case of pipelines or triggers.

2023-04-17 17:14 UTC, khrm commented
We have disable-ha property but we don't expose it in the operator. 

https://github.com/tektoncd/pipeline/blob/bd7a02f4c7785cc22faa7f260c1e2380126b6d28/cmd/controller/main.go#L62

But this setting isn't recommended, instead, just run a single replica of the controller.

2023-05-03 13:01 UTC, jkandasa commented
@yocum137 `disable-ha` support added in https://github.com/tektoncd/operator/pull/1458

2023-05-03 13:02 UTC, jkandasa commented
/close

2023-05-03 13:02 UTC, closed without merging