webhook yaml
tektoncd/operator pull request #202
Opened 2021-01-04 10:20 UTC by piyush-garg

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

2021-01-06 13:41 UTC, vdemeester requested changes
`.bin/ko` and `.bin/kustomize` shouldn't be in there 🙃 
(I think I forgot to add `.bin` to the `.gitignore` that said…)

2021-01-07 05:48 UTC, nikhil-thomas commented
/approve

2021-01-07 06:10 UTC, savitaashture approved these changes

2021-01-07 09:01 UTC, vdemeester approved these changes
/lgtm

2021-01-07 09:03 UTC, merged