[OpenShift] Fix forbidden error for community tasks
tektoncd/operator pull request #514
Opened 2021-11-19 14:46 UTC by savitaashture

# Changes

On disconnected cluster there could be scenario where community task URLs won't be reachable so as part of this PR adding changes to log the error and continue with next steps instead of returning error.

/cc @nikhil-thomas @concaf @vdemeester

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

2021-11-19 14:57 UTC, vdemeester approved these changes

2021-11-19 16:10 UTC, piyush-garg commented
/lgtm

2021-11-19 16:28 UTC, savitaashture commented
/hold

2021-11-22 04:10 UTC, savitaashture commented
/hold cancel

2021-11-22 04:14 UTC, savitaashture commented
/hold

2021-11-22 07:08 UTC, vdemeester approved these changes

2021-11-22 07:29 UTC, nikhil-thomas requested changes

2021-11-22 07:29 UTC, nikhil-thomas commented on pkg/reconciler/openshift/tektonaddon/tektonaddon.go
> +		logging.FromContext(ctx).Error("Failed to get community task ", err)
```suggestion
		logging.FromContext(ctx).Error("Failed to get community task: Skipping community tasks installation ", err)
```

2021-11-22 07:58 UTC, sm43 commented
/lgtm

2021-11-22 08:12 UTC, merged